// src/pages/about.jsx
import Layout from '~/components/Layout'

export default function About() {
  return (
    <Layout title="About">
      <h1>About Me</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error
        doloremque omnis animi, eligendi magni a voluptatum, vitae, consequuntur
        rerum illum odit fugit assumenda rem dolores inventore iste
        reprehenderit maxime! Iusto.
      </p>
    </Layout>
  )
}

// src/pages/About.vue
<template>
  <div>
    <h1>About Me</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error doloremque
      omnis animi, eligendi magni a voluptatum, vitae, consequuntur rerum illum
      odit fugit assumenda rem dolores inventore iste reprehenderit maxime!
      Iusto.
    </p>
  </div>
</template>

<script>
export default {
  metaInfo: {
    title: "About Me",
  },
};
</script>
