// src/routes/__layout.svelte
<script lang="ts">
	import { onMount, setContext } from 'svelte'
	import { fly } from 'svelte/transition'

	import { session, page } from '$app/stores'

	import BackToTop from '$components/BackToTop.svelte'
	import Hero from '$components/Hero.svelte'
	import NavBar from '$components/NavBar.svelte'
	import AvatarIntro from '$components/AvatarIntro.svelte'

	import { theme } from '$lib/stores'

	let container: Element

	onMount(() => {
		document.body.setAttribute('data-theme', $theme)
	})
</script>

{#if $session.introHasPlayed}
	{#if $page.path == '/'}
		<Hero target={container} />
	{/if}

	<NavBar />

	<BackToTop target={container} />

	<main bind:this={container} in:fly={{ x: -200, delay: 500 }}>
		<slot />
	</main>
{:else}
	<AvatarIntro />
{/if}

<style lang="scss">
	:global {
		* {
			box-sizing: border-box;
		}

		:root {
			font-size: 1rem;

			--header-height: 5rem;
			scroll-padding-top: calc(var(--header-height) + 1rem);

			--content-max: 800px;
			--content-width: min(100%, var(--content-max));

			scroll-behavior: smooth;
			--transition-duration: 250ms;
			--transition-function: ease-out;
			--transition: var(--transition-duration) var(--transition-function);
		}

		body {
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,
				Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;

			margin: 0 auto;
			padding: 0;

			line-height: 1.5;

			background-color: var(--color-bg-primary);
			color: var(--color-fg-primary);

			transition: background-color var(--transition);
		}

		body,
		body[data-theme='dark'] {
			--color-main: hsl(325, 100%, 80%);
			--color-accent: hsl(122, 91%, 21%);

			--color-bg-primary: hsl(0, 0%, 10%);
			--color-bg-secondary: hsl(0, 0%, 20%);

			--color-fg-primary: hsl(0, 0%, 90%);
			--color-fg-secondary: hsl(0, 0%, 80%);

			--color-shadow: hsla(0, 0%, 0%, 100%);
		}

		body[data-theme='light'] {
			--color-main: hsl(0, 0%, 40%);
			--color-accent: hsl(0, 0%, 60%);

			--color-bg-primary: hsl(0, 0%, 90%);
			--color-bg-secondary: hsl(0, 0%, 80%);

			--color-fg-primary: hsl(0, 0%, 10%);
			--color-fg-secondary: hsl(0, 0%, 20%);

			--color-shadow: hsla(0, 0%, 15%, 60%);
		}

		a {
			color: currentColor;
		}

		body[data-theme='dark'] ::selection {
			background-color: hsl(325, 45%, 60%);
		}

		body[data-theme='light'] ::selection {
			background-color: hsl(121, 32%, 71%);
		}
	}

	main {
		margin: 0 auto;

		width: var(--content-width);
		padding: 1em 2em;
	}
</style>

// src/components/Layout.jsx
import Link from 'next/link'
import Head from 'next/head'

const siteName = "Tim's Portfolio"

export default ({ children, home, title }) => (
  <div className="container">
    <Head>
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <link rel="icon" href="/favicon.png" type="image/png" />
      <title>{`${title} | ${siteName}`}</title>
    </Head>

    <header className="header">
      <strong>
        <Link href="/">Tim's Portfolio</Link>
      </strong>
      <nav className="nav">
        <Link href="/">
          <a className="nav__link">Home</a>
        </Link>
        <Link href="/about/">
          <a className="nav__link">About</a>
        </Link>
      </nav>
    </header>

    {children}

    <footer></footer>

    <style jsx global>{`
        :root {
          font-size: 14px;
        }

        a {
          color: currentColor;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
            Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
          margin: 0;
          padding: 0;
          line-height: 1.5;
        }

        body,
        body[data-theme='dark'] {
          --clr-main: hsl(323, 91%, 58%);
          --clr-accent: hsl(148, 91%, 58%);
          --clr-bg-primary: hsl(315, 15%, 18%);
          --clr-fg-primary: hsl(325, 90%, 97%);
        }

        body[data-theme='light'] {
          --clr-main: hsl(325, 88%, 66%);
          --clr-accent: hsl(148, 91%, 58%);
          --clr-bg-primary: hsl(0, 0%, 98%);
          --clr-fg-primary: hsl(150, 15%, 18%);
        }
      `}</style>

    <style jsx>{`
      .container {
        max-width: 1000px;
        margin: 0 auto;
        padding: 0 20px;
      }

      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1.5em;
        height: 5em;
      }

      .nav__link + .nav__link {
        margin-left: 20px;
      }
    `}</style>
  </div>
)
