// src/components/MobileNav.svelte
<script lang="ts">
    export let pages: {
        href: string
        name: string
    }[]

    export let current: string

    const openMargin = 50

    let lastScroll: number
    let scrollY: number

    let hidden: boolean = false

    function checkHidden(scroll: number) {
        if (scrollY === undefined) return
        const dy = scroll - lastScroll

        hidden = scrollY > openMargin && dy >= 0
        lastScroll = scroll
    }

    $: checkHidden(scrollY)
</script>

<svelte:window bind:scrollY />

{#if !hidden}
    <nav class="relative flex h-12 items-center justify-start px-5">
        <ul class="links">
            {#each pages as { href, name }}
                <li aria-current={current === href}>
                    <a {href}>{name}</a>
                </li>
            {/each}
        </ul>
    </nav>
{/if}

<style lang="postcss">
    .links {
        @apply flex h-full items-center gap-4;
    }
</style>

// src/components/MobileNav.tsx
import { createSignal, For, onMount } from 'solid-js'

export default function MobileNav(props: {
    pages: { href: string; name: string }[]
    current: string
}) {
    const [hidden, setHidden] = createSignal(false)

    onMount(() => {
        window.addEventListener('scroll', () => {
            setHidden(window.scrollY > 50)
        })
    })

    return (
        <div
            class="bg-gray-200 transition-transform"
            classList={{ 'translate-y-[-100%]': hidden() }}
        >
            <ul class="flex h-12 items-center justify-start gap-4 px-5">
                <For each={props.pages}>
                    {({ href, name }) => {
                        const current = () => props.current === href
                        return (
                            <li classList={{ underline: current() }}>
                                <a href={href}>{name}</a>
                            </li>
                        )
                    }}
                </For>
            </ul>
        </div>
    )
}
