// src/components/SketchCanvas.tsx
import type { Sketch } from '@sketches/types'
import { onCleanup, onMount } from 'solid-js'

export default function SketchCanvas(props: { slug: string }) {
    let canvas: HTMLCanvasElement
    let lastRequest: number

    onMount(async () => {
        const mod = await import(`../sketches/${props.slug}.ts`)
        const sketch = mod.default as Sketch

        const ctx = canvas.getContext(sketch.type)! as any

        if (sketch.init !== undefined) {
            sketch.init(ctx)
        }

        const tick = (t: DOMHighResTimeStamp) => {
            sketch.draw(ctx, t)
            lastRequest = requestAnimationFrame(tick)
        }

        lastRequest = requestAnimationFrame(tick)
    })

    onCleanup(() => cancelAnimationFrame(lastRequest))

    return <canvas ref={canvas!} width="600" height="600" tabindex="0" />
}

// src/components/SketchCanvas.svelte
<script lang="ts">
    import { onMount } from 'svelte'

    export let slug: string

    let canvas: HTMLCanvasElement

    onMount(async () => {
        const sketch = await import(`../sketches/${slug}.ts`)

        if (sketch.init !== undefined) {
            sketch.init(canvas)
        }

        const ctxType = sketch.ctxType ?? '2d'
        const ctx = canvas.getContext(ctxType)

        let lastRequest: number
        const tick = (t: DOMHighResTimeStamp) => {
            sketch.draw(ctx, t)
            lastRequest = requestAnimationFrame(tick)
        }

        lastRequest = requestAnimationFrame(tick)

        return () => cancelAnimationFrame(lastRequest)
    })
</script>

<canvas width="600" height="600" tabindex="0" bind:this={canvas} />
